#!/usr/bin/fish

set time

getopts $argv | while read -l key value
    switch $key
        case _
            set time (date -d @(math 60 '*' $value '+' (date +%s)) +%s)
        case u until 
            set time (date -d $value +%s)
    end
end

echo Screensaver delayed until (date -d @$time) 1>&2
echo %self

while test $time '-gt' (date +%s) >/dev/null
    xscreensaver-command -deactivate >/dev/null
    sleep 10
end
