#!/usr/bin/ruby
require "clipboard"

string = "fabulous"
string = ARGV.join(" ") unless ARGV.empty?

output = "༺✧･ﾟ: ✧･ﾟ: #{string.gsub(" ", "\u{3000}")} :･ﾟ✧:･ﾟ✧ ༻"

Clipboard.copy output
puts output
