#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch polybar

if type "xrandr"; then
  for mon in $(xrandr --query | awk '/\s+connected/{ print $1 }'); do
    MONITOR=$mon polybar --reload gambit &
  done
else
  polybar --reload gambit &
fi
